inc/languages/english/myalerts.lang.php
I was thinking to put name of the thread (2) on the new line, but I think this is enough
=> Minor improvement

inc/languages/english/admin/myalerts.lang.php
Fixes #135 - bug in admin lang file
=> Fixes #135 - bug in admin lang file

alerts.php, inc/plugins/MybbStuff/MyAlerts/templates/headericon.html, inc/plugins/MybbStuff/MyAlerts/templates/modal_content.html, inc/plugins/myalerts.php, jscripts/myalerts.js
=> Fix #139 Load modal via ajax

jscripts/myalerts.js
Fixes #146 - Fix deleting alerts in UCP panel
thx @WhiteNeo for his idea and code
=> Fixes #146 - Fix deleting alerts in UCP panel

inc/plugins/myalerts.php
=> Fixes #179 - Avatar dimensions description (ACP)

jscripts/myalerts.js
#177
All credits @White Neo (Dark Neo)
=> Fixes #177 - UCP - check for new alerts

inc/plugins/MybbStuff/MyAlerts/stylesheets/alerts.css
Fixes #182 - follow MyBB css style for td-trow1
=> Fixes #182 - follow MyBB css style for td-trow1

inc/plugins/MybbStuff/MyAlerts/templates/headericon.html
Fix #162 Modal window and overlay z-index
I did not text but this should work.
=> Fix #162 Modal window and overlay z-index

inc/plugins/myalerts.php
=> Fix #206 Incorrect information on installed alert types due to out-of-sync cache

inc/languages/english/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/src/Formatter/ThreadAuthorRatedFormatter.php, inc/plugins/myalerts.php
=> Add thread rating alert type

inc/languages/english/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/src/Formatter/ThreadAuthorRatedFormatter.php, inc/plugins/MybbStuff/MyAlerts/src/Formatter/ThreadAuthorVotedFormatter.php, inc/plugins/myalerts.php
=> Fix #213 Notification type - thread poll vote

inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php, inc/plugins/MybbStuff/MyAlerts/src/AlertTypeManager.php, inc/plugins/myalerts.php
=> Fix #214 Modify queries to support PostgreSQL

inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php
=> Fix #217 Add hook for marking alerts as read

inc/plugins/myalerts.php
Fixed: Add alerts when quoting own posts
=> Alert when quoting own post

inc/languages/english/myalerts.lang.php
=> Fixes #232 - replace <b> with <strong>

inc/plugins/myalerts.php
#193
depends on mybb/mybb#2870
=> Fix #193 Change myalerts_addAlert_pm() to use the PMDataHandler hook

inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php
=> Fix #241 Incorrect disabled alerts type check

inc/plugins/MybbStuff/MyAlerts/src/AlertTypeManager.php
Fixes #247.
Also does some slight code reformatitng to fix indentations and such.
=> Fix #247 - remove ID before trying to add type

alerts.php
=> Fixes "unknown" location in WOL

inc/plugins/MybbStuff/MyAlerts/templates/alert_row.html
Padding issue in modal will be fixed in another PR.
=> Fixes #144

alerts.php
=> Remove duplication in alert.php- #251

inc/tasks/myalerts.php
=> Fixes #243 - Delete old unread alerts

inc/tasks/myalerts.php, php_errors.log
* Add closing paren.
* Correct pairing of (un)read time intervals
with `unread` column in conditional.
* Delete extraneous blank line.
=> Fix #271: broken conditional in task file

inc/languages/english/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/templates/alert_row.html, inc/plugins/MybbStuff/MyAlerts/templates/alert_row_popup.html, inc/plugins/myalerts.php, jscripts/myalerts.js
- PHP part added
- JS part added
- lang part added
- templates edited
Tested and should be fine, thx Shade and Rocketfood for their ideas :)
Resolves #122
=> Add AJAX read/delete for modal and alert page

inc/plugins/myalerts.php
=> Fixes #245: no alert when spaces in quoted username

alerts.php, inc/plugins/myalerts.php
Also includes fixes for a few warnings (and potential warnings) not mentioned in the Community Forums post linked from issue #278.
Resolves #278
=> Fix #278: Warnings are emitted under PHP 8

inc/plugins/myalerts.php
=> Fix #289: Client plugin alert formatting in the modal

inc/plugins/MybbStuff/MyAlerts/templates/usercp_nav.html
=> Fix #287: Persistence of the expand/collapse state in the UserCP

alerts.php, inc/languages/english/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php, inc/plugins/MybbStuff/MyAlerts/templates/modal_content.html, inc/plugins/MybbStuff/MyAlerts/templates/page.html, inc/plugins/myalerts.php, jscripts/myalerts.js
=> Fix #281: "Mark all read" functionality is missing

README.md, inc/plugins/MybbStuff/MyAlerts/src/AlertFormatterManager.php, inc/plugins/myalerts.php
Per Euan's preference in this comment:
https://github.com/MyBBStuff/MyAlerts/issues/289#issuecomment-1637119606
Resolves #289
=> Refix #289: Client plugin alert formatting in the modal

alerts.php, inc/languages/english/admin/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/templates/js_popup.html, inc/plugins/myalerts.php, jscripts/myalerts.js
=> Fix #298: Implement a "Backwards compatibility mode" setting

inc/plugins/MybbStuff/MyAlerts/stylesheets/alerts.css
Resolves #300
Reverts the unnecessary fix in #286 for apparently bogus issue #285.
=> Fix #300: Revert #286 for unstyled read alerts #285

inc/plugins/myalerts.php
=> Fix #302: Redundant code in myalerts_xmlhttp() for myalerts_delete

inc/plugins/myalerts.php
=> Fix #306: Warning re unset variable $expaltext

alerts.php, inc/languages/english/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/templates/alert_row_more.html, inc/plugins/MybbStuff/MyAlerts/templates/js_popup.html, inc/plugins/MybbStuff/MyAlerts/templates/page.html, inc/plugins/myalerts.php, jscripts/myalerts.js
=> Fix #304: Alert (auto)updating is broken

alerts.php, inc/plugins/myalerts.php
=> (Redo of) Fix #283: Visits to alerts.php shouldn't mark all read

inc/plugins/MybbStuff/MyAlerts/templates/js_popup.html, inc/plugins/myalerts.php, jscripts/myalerts.js
...when an individual alert is marked read / deleted via the modal.
Resolves #312
=> Fix #312: Alerts count in title and header icon not updating

jscripts/myalerts.js
=> Fix #341: JS method markAllRead() should call updateVisibleCounts()

jscripts/myalerts.js
=> Fix #339: Bug when updating UCP MyAlerts page sidebar count

inc/plugins/MybbStuff/MyAlerts/stylesheets/alerts.css
=> Fix #331: UCP icons sometimes wrongly styled

inc/plugins/myalerts.php
Fixes #249
(Or, at least, implements one of @Eldenroot's suggestions in the comments of that issue).
=> Fix #249 by erroring out when missing PluginLibrary or Plugins.Core

admin/modules/config/myalerts.php, inc/languages/english/admin/myalerts.lang.php, inc/plugins/MybbStuff/MyAlerts/src/AlertTypeManager.php, inc/plugins/MybbStuff/MyAlerts/src/Entity/AlertType.php, inc/plugins/myalerts.php
=> Fix #141: Add default settings for alerts types

alerts.php, inc/languages/english/myalerts.lang.php
=> Fix #328: wrong redirect message on deleting read alerts

inc/plugins/myalerts.php
=> Fix #324: "Can only view own threads?" permission not respected

inc/plugins/myalerts.php
=> Fix #118 and #159: delete/mark read alert on view/delete PM

inc/plugins/MybbStuff/MyAlerts/src/AlertManager.php, inc/plugins/myalerts.php
=> Fix #110: Change unread -> read alert when user visit the post

inc/plugins/myalerts.php
=> Fix #23: Recognize when edit (add/remove quote alerts)

inc/plugins/MybbStuff/MyAlerts/templates/alert_row.html, inc/plugins/MybbStuff/MyAlerts/templates/alert_row_popup.html
Add width tag and add align missing tag
Fixes #319
=> Fixes #319 - Time/date of alert - center text

inc/plugins/myalerts.php
* Update the permission-checking code in `myalerts_update_quoted()`.
* Refactor `myalerts_alert_quoted()` to use the new `myalerts_get_quoted_usernames()` and `myalerts_usernames_to_uids()` functions.
=> Implement TODO items flagged in recent PRs

inc/plugins/myalerts.php
This was a typo in the recent PR #344.
=> Correct `$mybb->user['name']` to `$mybb->user['username']`

inc/plugins/myalerts.php
I accidentally omitted the plugin file's indentation fixes when submitting PR #345. This corrects that omission.
=> Fix indentation in plugin file

inc/plugins/myalerts.php, jscripts/myalerts.js
=> Fix #349: Assumptions in the JS to update visible alert counts

inc/plugins/MybbStuff/MyAlerts/templates/modal_content.html, jscripts/myalerts.js
=> Fix #356: Non-table layouts break client-side updating

jscripts/myalerts.js
=> Fixes #352

inc/tasks/myalerts.php
=> Fix #362: Task to delete old alerts fails to do that

inc/plugins/MybbStuff/MyAlerts/templates/js_popup.html, jscripts/myalerts.js
=> Fix #366: Parenthesised alert count sometimes not offset with a space
